import Link from "next/link";
const lessons = [["01","函数的概念与表示","28 分钟"],["02","函数的基本性质","35 分钟"],["03","函数的零点与方程","32 分钟"],["04","导数的概念与几何意义","41 分钟"],["05","导数与函数单调性","38 分钟"],["06","极值与最值问题","44 分钟"]];
export default function CoursePage(){return <main className="inner-page">
  <header className="inner-nav"><Link href="/" className="logo"><span className="logo-mark">✦</span><span>逐光课堂</span></Link><nav><Link href="/">首页</Link><b>课程详情</b><span>学习中心</span></nav><Link href="/profile" className="user-chip"><span className="avatar">朱</span><span><small>今日剩余 1/2</small>朱辰宇</span></Link></header>
  <div className="breadcrumb"><Link href="/">首页</Link><span>›</span><Link href="/#courses">数学课程</Link><span>›</span><b>函数与导数专题突破</b></div>
  <section className="course-hero"><div className="course-visual"><span>数学 · 专题突破</span><strong>f′(x)</strong><em>函数与导数</em></div><div className="course-summary"><span className="status-pill">正在学习</span><h1>函数与导数专题突破</h1><p>从函数核心概念到导数综合应用，搭建完整知识网络。通过典型例题与高考真题，掌握常考模型与规范解题步骤。</p><div className="meta-row"><span><b>24</b><small>总课时</small></span><span><b>16</b><small>已完成</small></span><span><b>4.9</b><small>课程评分</small></span><span><b>周言</b><small>授课老师</small></span></div><Link className="btn primary" href="/learn/derivative-monotonicity">继续学习 <span>→</span></Link></div></section>
  <section className="course-main"><div className="lesson-panel"><div className="panel-title"><div><span className="kicker">课程目录</span><h2>循序渐进，稳步掌握</h2></div><span>已完成 68%</span></div><div className="wide-bar"><i /></div>
    <div className="chapter"><h3>第一章　函数基础与性质 <span>4 / 4 完成</span></h3>{lessons.slice(0,4).map(l=><div className="lesson done" key={l[0]}><span className="lesson-no">{l[0]}</span><span className="play-dot">✓</span><div><b>{l[1]}</b><small>{l[2]} · 已学完</small></div><span className="lesson-action">复习</span></div>)}</div>
    <div className="chapter"><h3>第二章　导数及其应用 <span>0 / 6 完成</span></h3>{lessons.slice(4).map((l,i)=><Link href="/learn/derivative-monotonicity" className={`lesson ${i===0?"current":""}`} key={l[0]}><span className="lesson-no">{l[0]}</span><span className="play-dot">▶</span><div><b>{l[1]}</b><small>{l[2]} · 视频课程</small></div><span className="lesson-action">{i===0?"继续学习":"开始"}</span></Link>)}</div>
  </div><aside><div className="side-card remaining"><small>今日学习计划</small><strong>1<em>/2</em></strong><p>剩余课程</p><div className="wide-bar"><i /></div><span>完成这一节，今日计划就完成啦</span></div><div className="side-card"><h3>课程资料</h3><a>▤ 函数与导数公式清单 <span>下载</span></a><a>▤ 第一章配套练习 <span>查看</span></a><a>▤ 近五年高考真题 <span>查看</span></a></div></aside></section>
</main>}
